"use client";
import './globals.css';
import './embla.css';
import { Manrope, Inter, IBM_Plex_Mono } from 'next/font/google';
import { Provider } from 'react-redux';
import store from '../store/index';
// import { useDispatch, useSelector } from 'react-redux';
// import { setUser } from '@/store/actions/authAction';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { PersistGate } from 'reduxjs-toolkit-persist/integration/react';
import { persistStore } from 'reduxjs-toolkit-persist';
import { Analytics } from '@vercel/analytics/react';
import Entry from '@/components/Entry';

/* export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

const display = Manrope({
  subsets: ['latin'],
  variable: '--font-display',
  display: 'swap',
});
const sans = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
});
const mono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-mono',
  display: 'swap',
});

const persistor = persistStore(store);

export default function RootLayout({ children }) {
/*  const dispatch = useDispatch();
   useEffect(() => {
    dispatch(setUser());
  }, []);  */
  return (
     <html lang="en" className={`h-full ${display.variable} ${sans.variable} ${mono.variable}`}>
     <body className="h-full">
        <Provider store={store}> 
          <PersistGate persistor={persistor}>
             <div className="">
            {/*     <Navbar2 />  */}
             <Entry>{children}</Entry>
              {/*     {children}  */}
                 <Analytics />
               <ToastContainer pauseOnHover={false} position="top-center" />
             </div>
           </PersistGate>
       </Provider> 
      
     </body>
   </html>
  )
}
