"use client";
import './globals.css';
// import { Inter } from 'next/font/google';
// import Navbar from '../components/Navbar';
import Navbar2 from '../components/Navbar2';
import { Provider } from 'react-redux';
import store from '../store/index';
import { useDispatch, useSelector } from 'react-redux';
import { setUser } from '@/store/actions/authAction';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

// const inter = Inter({ subsets: ['latin'] })

/* export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

export default function RootLayout({ children }) {
  // const dispatch = useDispatch();
 /*  useEffect(() => {
    dispatch(setUser());
  }, []); */
  return (
     <html lang="en" className="h-full">
     <body className="h-full">
        <Provider store={store}> 
           <div className="">
             <Navbar2 /> 
            {/*  <Entry children={...children} /> */}
             {children} 
             <ToastContainer pauseOnHover={false} position="top-center" />
           </div>
       </Provider> 
     </body>
   </html>
  )
}
